#!/bin/bash
#
# /etc/init.d/stratuslab-vmc
#
# StratusLab VM Controller
#
# chkconfig: 345 90 10
# pidfile: /var/run/stratuslab-vmc.pid

# Source function library.
. /etc/rc.d/init.d/functions

case "$1" in
    start)
        echo "Starting stratuslab-vmc..."
        /usr/sbin/stratuslab-vmc.py start
        touch /var/lock/subsys/stratuslab-vmc
        ;;
    stop)
        echo "Shutting down stratuslab-vmc..."
        /usr/sbin/stratuslab-vmc.py stop
        rm -f /var/lock/subsys/stratuslab-vmc
        ;;
    status)
        status -p /var/run/stratuslab-vmc.pid stratuslab-vmc
        ;;
    restart)
        /usr/sbin/stratuslab-vmc.py restart
        ;;
    reload)
        /usr/sbin/stratuslab-vmc.py restart
        ;;
    *)
        echo "Usage: stratuslab-vmc {start|stop|status|reload|restart"
        exit 1
        ;;
esac
