#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys

import os

sys.path.append(os.path.join('..', 'src'))
sys.path.append(os.path.join(os.sep, 'usr', 'lib', 'stratuslab'))

from stratuslab import FileAppender

# initialize console logging
import stratuslab.api.LogUtil as LogUtil

LogUtil.get_console_logger()


class MainProgram:
    '''A command-line program to perform StratusLab RPM/DEB post-installation.'''

    def __init__(self):
        self.doWork()

    def doWork(self):
        appender = FileAppender.FileAppender(os.path.join(os.sep, 'etc', 'rc.local'))

        oneStartCommand = 'su oneadmin; one start'
        appender.insertAtTheEnd(oneStartCommand)

        print '\nSo far so good...\n'
        print 'To complete the installation of StratusLab, please run:'
        print '    stratus-config ... to configure your cloud'
        print '    stratus-install ... for each physical machine (front-end and nodes)'
        print '                        which will take part in the cloud'
        print '\nThank you for installing StratusLab.'
        print 'Let us know how it goes: support@stratuslab.eu\n'


if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'

