#!/usr/bin/env python

import os
import sys
from optparse import OptionParser

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.marketplace.Downloader import Downloader
from stratuslab.ConfigHolder import ConfigHolder

def main():
    usage = "Usage: %prog --get-element <ELEMENT> <marketplace image URL>"
    
    parser = OptionParser(usage=usage)
    
    parser.add_option('--get-element', dest='element', help='Element to get.',
        metavar='ELEMENT', default=None)
    options, args = parser.parse_args()
    
    try:
        imageEndpoint = args[0]
    except IndexError:
        print parser.usage
        sys.exit(1)
    
    if not options.element:
        print parser.usage
        sys.exit(1)
    else:
        element = options.element
    
    marketplaceEndpoint, imageId = imageEndpoint.rsplit('/', 1)
    
    configHolder = ConfigHolder()
    configHolder.set('endpoint', marketplaceEndpoint)
    
    downloader = Downloader(configHolder)
    downloader.downloadManifestByImageId(imageId)
    
    if element == 'location':
        value = downloader.getImageLocations()
        value = value[0]
    else:
        value = downloader.getImageElementValue(element)
    print value

if __name__ == "__main__":
    try:
        main()
    except Exception, ex:
        print >> sys.stderr, str(ex)
        sys.exit(1)
