#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys
from optparse import OptionParser, OptionGroup

sys.path.append('/var/lib/stratuslab/python')

import stratuslab.Util as Util
from stratuslab import Defaults
from stratuslab.CommandBase import CommandBaseSysadmin
from stratuslab.ConfigHolder import ConfigHolder
from stratuslab.installator.BaseInstallator import BaseInstallator

class MainProgram(CommandBaseSysadmin):
    '''A command-line program to install StratusLab.'''

    def __init__(self):
        super(MainProgram, self).__init__()

    def parse(self):
        usage = '%prog [options]'

        self.parser.usage = usage
        
        self.parser.add_option('-n', '--node', dest='nodeAddr', 
                               help='IP address or hostname of the node to configure',
                               default=None, metavar='ADDRESS')
        self.parser.add_option('--apprepo', dest='appRepoAddr', 
                               help='IP address or hostname of the appliance repository to configure',
                               default=None, metavar='ADDRESS')
        self.parser.add_option('-k', '--private-key', dest='privateKey', 
                               help='private key for ssh node connection', metavar='FILENAME',
                               default=None)
        
        componentGroup = OptionGroup(self.parser, 'Available components', 
                                     'Unless specify all components will be selected')
        self.parser.add_option_group(componentGroup)
        self._addComponentsOptions(componentGroup)
        
        installGroup = OptionGroup(self.parser, 'Installation options', 
                                   'Unless specify will perform all the actions')
        self.parser.add_option_group(installGroup)
        
        installGroup.add_option('--install', dest='installStep',
                               help='Install all or selected components', 
                               action='store_true', default=False)
        installGroup.add_option('--setup', dest='setupStep',
                               help='Setup all or selected components', 
                               action='store_true', default=False)
        installGroup.add_option('--start', dest='startServices',
                               help='Start all or selected components', 
                               action='store_true', default=False)
        
        oneGroup = OptionGroup(self.parser, 'OpenNebula options')
        self.parser.add_option_group(oneGroup)
        
        oneGroup.add_option('-t', '--template', dest='onedTpl', 
                               help='ONe daemon template', metavar='TEMPLATE',
                               default=os.path.join(Util.getTemplateDir(), 'oned.conf.tpl'))
        oneGroup.add_option('--im', dest='infoDriver', 
                               help='information driver', metavar='IM_NAME', default=None)
        oneGroup.add_option('--vmm', dest='virtDriver',
                               help='virtualization driver', metavar='VM_NAME', default=None)
        oneGroup.add_option('--tm', dest='transfertDriver', 
                               help='transfert driver', metavar='VM_NAME', default=None)
        
        self.options, _ = self.parser.parse_args()

    def checkOptions(self):
        if self._noInstallStepSelected():
            self.options.installStep = True
            self.options.setupStep = True
            self.options.startServices = True

    def _noInstallStepSelected(self):
        return not self.options.installStep and not self.options.setupStep and self.options.startService
    
    def _addComponentsOptions(self, parser):
        for name in BaseInstallator.availableInstallator().keys():
            parser.add_option('--%s' % name, dest='install%s' % name.title(), 
                               help='%s component' % name.title(),
                               action='store_true', default=False)

    def doWork(self):
        config = ConfigHolder.configFileToDict(self.options.configFile)        
        configHolder = ConfigHolder(self.options.__dict__, config)
        
        installator = BaseInstallator()
        installator.runInstallator(configHolder)
        

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
