#!/usr/bin/env python

import re
import os
import sys
from optparse import OptionParser

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.marketplace.Downloader import Downloader
from stratuslab.ConfigHolder import ConfigHolder
from stratuslab.Image import Image 
import stratuslab.Util as Util

USAGE = """Usage: %prog --get-element <ELEMENT> <marketplace image URL>
<marketplace image URL> - a valid URL. (http://example.com/dir/imageID)"""

parser = OptionParser(usage=USAGE)

def _exitWithUsage(msg=''):
    if msg:
        print >> sys.stderr, msg
    print >> sys.stderr, parser.usage
    raise SystemExit(1)

def main():
    
    parser.add_option('--get-element', dest='element', help='Element to get.',
        metavar='ELEMENT', default=None)
    options, args = parser.parse_args()
    
    try:
        imageEndpoint = args[0]
    except IndexError:
        _exitWithUsage()
    else:
        if Image.re_imageUrl.match(imageEndpoint):
            _exitWithUsage('ERROR: An image URL was given is not MarketPlace image URL.')

    if not options.element:
        _exitWithUsage()
    else:
        element = options.element

    configHolder = ConfigHolder()
    
    try:
        _uri, imageId = imageEndpoint.rsplit('/', 1)
        marketplaceEndpoint = Util.getProtoHostnamePortFromUri(_uri)
    except ValueError:
        _exitWithUsage()

    configHolder = ConfigHolder()
    configHolder.set('marketplaceEndpoint', marketplaceEndpoint)
    
    downloader = Downloader(configHolder)
    downloader.downloadManifestByImageId(imageId)
    
    if element == 'location':
        value = downloader.getImageLocations()
        value = value[0]
    else:
        value = downloader.getImageElementValue(element)
    print value

if __name__ == "__main__":
    main()
