#!/usr/bin/env python

import os
import sys
from optparse import OptionParser

sys.path.append('/usr/lib/stratuslab')
sys.path.append(os.path.abspath('%s/../src/' % os.path.abspath(os.path.dirname(__file__))))

from stratuslab.Util import modulePath
from stratuslab.CommandBase import CommandBase
from stratuslab.InstallatorFactory import InstallatorFactory
from stratuslab.Util import parseConfig

class MainProgram(CommandBase):
    '''A command-line program to install StratusLab.'''

    def __init__(self):
        super(MainProgram, self).__init__()

    def parse(self):
        usage = 'usage: %prog [options]'

        self.parser.usage = usage
        self.parser.add_option('-c', '--config', dest='configFile', 
                               help='configuration file', metavar='FILE',
                               default='%s/conf/stratuslab.cfg' % modulePath)
        self.parser.add_option('-n', '--node', dest='nodeAddr', 
                               help='IP address or hostname of the node to configure',
                               default=None, metavar='ADDRESS')
        self.parser.add_option('--apprepo', dest='appRepoAddr', 
                               help='IP address or hostname of the appliance repository to configure',
                               default=None, metavar='ADDRESS')
        self.parser.add_option('-k', '--private-key', dest='privateKey', 
                               help='private key for ssh node connection', metavar='FILENAME',
                               default=None)
        self.parser.add_option('--install', dest='onlyInstall',
                               help='Only install packages, don\'t perform setup', 
                               action='store_true', default=None)
        self.parser.add_option('--setup', dest='onlySetup',
                               help='Only setup system, don\'t install packages', 
                               action='store_true', default=None)
        
        # ONE specific parameters
        self.parser.add_option('-t', '--template', dest='onedTpl', 
                               help='ONe daemon template', metavar='TEMPLATE',
                               default='%s/share/template/oned.conf.tpl' % modulePath)
        self.parser.add_option('--im', dest='infoDriver', 
                               help='information driver', metavar='IM_NAME', default=None)
        self.parser.add_option('--vmm', dest='virtDriver',
                               help='virtualization driver', metavar='VM_NAME', default=None)
        self.parser.add_option('--tm', dest='transfertDriver', 
                               help='transfert driver', metavar='VM_NAME', default=None)
        
        self.options, _ = self.parser.parse_args()

    def checkOptions(self):
        if self.options.onlyInstall and self.options.onlySetup:
            self.parser.error('--install and --setup are mutually exclusive.')

    def doWork(self):
        config = parseConfig(self.options.configFile)        
        self.installator = InstallatorFactory().getInstallator()
        self.installator.runInstall(self.options, config)
        

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
