#!/bin/sh -e

[ -e /dev/hdd ] && DEVICE=hdd || DEVICE=sr0

CONTEXT_DIR=/mnt/stratuslab
mkdir -p $CONTEXT_DIR

mount -t iso9660 /dev/$DEVICE $CONTEXT_DIR

if [ -f $CONTEXT_DIR/context.sh ]; then
  $CONTEXT_DIR/init.sh
fi

