#!/usr/bin/env python

#
# Copyright (c) 2013, Centre National de la Recherche Scientifique (CNRS)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys

sys.path.append('/var/lib/stratuslab/python')

import libvirt

# initialize console logging
import stratuslab.api.LogUtil as LogUtil

LogUtil.get_console_logger()

LIBVIRT_URI = 'qemu:///system'

TIMEOUT = 300  # seconds
POLL_INTERVAL = 5  # seconds


class MainProgram(object):
    """
    Reboot a virtual machine (domain).  The domain ID is required.
    """

    def execute(self, checkpoint_path):
        conn = libvirt.open(LIBVIRT_URI)
        domain = conn.lookupByID(checkpoint_path)
        domain.reboot()


if __name__ == '__main__':

    domain_id = None
    try:
        if len(sys.argv) > 1:
            domain_id = int(sys.argv[1])
        else:
            msg = 'missing domain ID'
            LogUtil.error(msg)
            raise Exception(msg)

        MainProgram().execute(domain_id)
    except:
        msg = 'could not reboot domain %d' % domain_id
        LogUtil.error(msg)
        LogUtil.exception(msg)
        raise
