#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys
from optparse import OptionParser

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.Util import modulePath
from stratuslab.Util import printDetail
from stratuslab.Util import printError
from stratuslab.CommandBase import CommandBase
from stratuslab.ConfigHolder import ConfigHolder
from stratuslab.AuthnCommand import AuthnCommand
from stratuslab.Signator import Signator


class MainProgram(AuthnCommand):
    '''A command-line program to sign image manifest.'''

    def __init__(self):
        self.manifestFile = None
        self.args = None
        super(MainProgram, self).__init__()

    def parse(self):
        AuthnCommand.addP12CertOptions(self.parser)

        self.parser.usage='''%prog [options] [manifest-file]'''

        self.parser.add_option('--output', dest='outputManifestFile',
                help='newly signed manifest file (default [manifest-file].sign)',
                default=None)

        self.options, self.args = self.parser.parse_args()

    def checkOptions(self):
        if not self.args:
            self.parser.error('Missing manifest file')

        self.manifestFile = self.args[0]

        isFile = os.path.isfile(self.manifestFile)
        exists = os.path.exists(self.manifestFile)
        if not (exists and isFile):
            self.parser.error('Manifest file doesn\'t exist or is not a file')
            
        AuthnCommand.checkP12CertOptionsOnly(self)


    def doWork(self):
        configHolder = ConfigHolder(self.options.__dict__)
        signator = Signator(self.manifestFile, configHolder)
        isError = signator.sign()
        if isError:
            printError('Error signing manifest file')
        else:
            printDetail('Manifest file successfully signed: %s' % signator.outputManifestFile)

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
