#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.Runner import Runner
from stratuslab.Runnable import Runnable
from stratuslab.ConfigHolder import ConfigHolder
from stratuslab.Util import printAction
from stratuslab.Util import printStep


class MainProgram(Runnable):
    '''A command-line program to run a virtual machine.'''

    def parse(self):
        options = Runner.defaultRunOptions()

        self.parser.add_option('-n', '--number', dest='instanceNumber',
                help='number of machines to start (default 1)', metavar='INT',
                default=options['instanceNumber'], type='int')

        self.parser.add_option('--local-ip', dest='isLocalIp', action='store_true',
                help='By default, virtual machines are assigned a public IP address. ' \
                'With this option, a local address is provided, which means that it ' \
                'not be reachable from the outside, but will be reachable from other ' \
                'instances in the same data-center.',
                default=False)

        self.parser.add_option('--private-ip', dest='isPrivateIp', action='store_true',
                help='By default, virtual machines are assigned a public IP address. ' \
                'With this option, a private address is provided, which means that it ' \
                'not be reachable anywhere. This is useful for instances that initiate '\
                'the connection to other machinces.',
                default=False)

        self.parser.add_option('--save', dest='saveDisk', action='store_true',
                help='save image after VM shutdown',
                default=False)

        self.parser.add_option('-o', '--output', dest='outVmIdsFile',
                help='save vm-id to a file', metavar='FILE',
                default=None)

        self.parser.add_option('--extra-disk', dest='extraDiskSize',
                help='extra data disk size in GB', metavar='INT',
                action='callback', callback=self.diskSizeOptionCallback,
                default=0, type='int')

        self.parser.add_option('--qcow-disk-format', dest='useQcowDiskFormat',
                help='launch instance from an image in qcow2 disk format. This option requires ',
                action='store_true',
                default=False)

        self.parser.add_option('--address', dest='specificAddressRequest',
                help='request a specific ip address',
                metavar='IP', default=None)

        self.parser.add_option('--no-check-image-url', dest='noCheckImageUrl',
                help='Do not check image availability.',
                action='store_true',
                default=False)

        self.parser.add_option('--vm-name', dest='vmName',
                help='name of VM. If not given, a default name will be assigned by cloud layer.',
                metavar='NAME', default=options['vmName'])

        super(MainProgram, self).parse()

    def diskSizeOptionCallback(self, option, opt_str, value, parser):
        setattr(parser.values, option.dest, 1024*value)

    def doWork(self):
        configHolder = ConfigHolder(self.options.__dict__)
        runner = Runner(self.image, configHolder)
        printAction('Starting machines')
        runner.runInstance()
        printStep('Done!')

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
