#!/usr/bin/env python

import os
import sys

sys.path.append('/var/lib/stratuslab/python')
sys.path.append(os.path.abspath('%s/../../../../../src/' % os.path.abspath(os.path.dirname(__file__))))

from stratuslab.Runner import Runner
from stratuslab.Runnable import Runnable

class MainProgram(Runnable):
    '''A command-line program to run a virtual machine.'''

    def parse(self):
        options = Runner.defaultRunOptions()
        
        self.parser.add_option('-n', '--number', dest='instanceNumber',
                help='number of machines to start (default 1)', metavar='INT',
                default=options['instanceNumber'], type='int')

        self.parser.add_option('--save', dest='saveDisk', action='store_true',
                help='save image after VM shutdown',
                default=False)

        super(MainProgram, self).parse()

    def doWork(self):
        runner = Runner(self.image, self.options.__dict__)
        runner.runInstance()

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
