#!/usr/bin/env python

import os
import sys

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.Runner import Runner
from stratuslab.Runnable import Runnable
from stratuslab.ConfigHolder import ConfigHolder

class MainProgram(Runnable):
    '''A command-line program to run a virtual machine.'''

    def parse(self):
        options = Runner.defaultRunOptions()
        
        self.parser.add_option('-n', '--number', dest='instanceNumber',
                help='number of machines to start (default 1)', metavar='INT',
                default=options['instanceNumber'], type='int')

        self.parser.add_option('--save', dest='saveDisk', action='store_true',
                help='save image after VM shutdown',
                default=False)

        super(MainProgram, self).parse()

    def doWork(self):
        configHolder = ConfigHolder(self.options.__dict__)
        runner = Runner(self.image, configHolder)
        runner.runInstance()

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
