#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.CommandBase import CommandBase
from stratuslab.Util import manifestExt
from stratuslab.Uploader import Uploader

class MainProgram(CommandBase):
    '''A command-line program to upload StratusLab appliance.'''

    def __init__(self):
        self.manifest = None
        super(MainProgram, self).__init__()

    def parse(self):
        self.parser.usage = 'usage: %prog [options] manifest'
        Uploader.buildUploadParser(self.parser)
                
        self.options, self.args = self.parser.parse_args()

    def checkOptions(self):
        if self.options.listCompressionFormat:
            Uploader.availableCompressionFormat(True)
        
        if len(self.args) != 1:
            self.parser.error('Please specify an appliance manifest')
        self.manifest = self.args[0]

        Uploader.checkUploadOptions(self.options, self.parser)

        if not self.manifest.endswith(manifestExt):
            self.parser.error('Manifest must ends with %s' % manifestExt)
        if not os.path.isfile(self.manifest):
            self.parser.error('Appliance manifest does not exist')
        if not os.path.isfile(self.manifest.replace(manifestExt, '')):
            self.parser.error('Appliance does not exist')

    def doWork(self):
        uploader = Uploader(self.manifest, self.options.__dict__)
        uploader.start()
        

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
