#!/usr/bin/env python

#
# Copyright (c) 2013, Centre National de la Recherche Scientifique (CNRS)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys

sys.path.append('/var/lib/stratuslab/python')

import libvirt

# initialize console logging
import stratuslab.api.LogUtil as LogUtil

LogUtil.get_console_logger()

LIBVIRT_URI = 'qemu:///system'


class MainProgram(object):
    """
    Save the state of a virtual machine (domain).  This also suspends and
    removes the given domain.
    """

    def execute(self, domain_id, checkpoint_file):
        conn = libvirt.open(LIBVIRT_URI)
        domain = conn.lookupByID(domain_id)
        domain.save(checkpoint_file)

        LogUtil.info('saved domain %d, %s' % (domain.ID(), domain.UUIDString()))


if __name__ == '__main__':

    domain_id = -1
    checkpoint_file = None
    try:
        if len(sys.argv) > 2:
            domain_id = int(sys.argv[1])
            checkpoint_file = sys.argv[2]
        else:
            msg = 'missing domain ID or checkpoint filename'
            LogUtil.error(msg)
            raise Exception(msg)

        MainProgram().execute(domain_id, checkpoint_file)
    except:
        msg = 'could not save domain %d to %s' % (domain_id, checkpoint_file)
        LogUtil.error(msg)
        LogUtil.exception(msg)
        raise
