#!/usr/bin/env python

import os
import sys
from optparse import OptionParser
#from optparse import OptionGroup

sys.path.append('/usr/lib/stratuslab')
sys.path.append(os.path.abspath('%s/../src/' % os.path.abspath(os.path.dirname(__file__))))

import stratuslab
from stratuslab.CommandBase import CommandBase
from stratuslab.Testor import Testor
from stratuslab.Util import parseConfig

class MainProgram(CommandBase):
    '''A command-line program to test StratusLab.'''

    def __init__(self):
        super(MainProgram, self).__init__()

    def parse(self):
        modulePath = os.path.abspath('%s/../' % os.path.abspath(os.path.dirname(stratuslab.__file__)))
        usage = '''usage: %prog [options] [test] ...\n\n
where test is a comma separated list of tests, according to the name provided by -l/--list.'''
        

        self.parser = OptionParser(usage=usage)
        self.parser.add_option('-c', '--config', dest='configFile', 
                               help='configuration file', metavar='PATH',
                               default='%s/conf/stratuslab.cfg' % modulePath)
        
        self.parser.add_option('-l', '--list', dest='listTests', 
                               help='list available tests', action='store_true',
                               default=False)
        
        self.options, self.tests = self.parser.parse_args()

    def doWork(self):
        config = parseConfig(self.options.configFile)
        Testor.config = config
        Testor.options = self.options.__dict__
        Testor.testNames = self.tests
        testor = Testor()
        
        if self.options.listTests:
            self._listTests(testor)
        else:
            self._runTests(testor)

    def _listTests(self, testor):
        testor.listTests()

    def _runTests(self, testor):
        wasSuccessful = testor.runTests()
        if not wasSuccessful:
            sys.exit(-1)
        

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
        sys.exit(1)
