#!/usr/bin/env python

import os
import sys
from optparse import OptionParser
from optparse import OptionGroup

sys.path.append('/usr/lib/stratuslab')
sys.path.append(os.path.abspath('%s/../src/' % os.path.abspath(os.path.dirname(__file__))))

import stratuslab
from stratuslab.CommandBase import CommandBase
from stratuslab.Testor import Testor
from stratuslab.Util import parseConfig

class MainProgram(CommandBase):
    '''A command-line program to test StratusLab.'''

    def __init__(self):
        super(MainProgram, self).__init__()

    def parse(self):
        modulePath = os.path.abspath('%s/../' % os.path.abspath(os.path.dirname(stratuslab.__file__)))
        usage = 'usage: %prog [options]'

        self.parser = OptionParser(usage=usage)
        self.parser.add_option('-c', '--config', dest='configFile', 
            help='configuration file', metavar='PATH', 
            default='%s/conf/stratuslab.cfg' % modulePath)
        self.parser.add_option('-t', '--template', dest='vmTemplate', 
            help='VM template used for tests', metavar='PATH', 
            default='%s/share/vm/ttylinux-test.one' % modulePath)
        
        #testsGroup = OptionGroup(self.parser, 'Available tests',
        #    'Order of these options doesn\'t matter')
        #testsGroup.add_option('-s', '--run-machine', dest='runMachineTest',
        #    help='deploy a VM checks it run and stop it', action='store_true',
        #    default=False)
        #self.parser.add_option_group(testsGroup)
        
        self.options, _ = self.parser.parse_args()

    def doWork(self):
        config = parseConfig(self.options.configFile)
        self.testor = Testor(config, self.options)
        self.testor.runTests()


if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
        sys.exit(1)
