#!/usr/bin/env python

import os
import sys

sys.path.append('/usr/lib/stratuslab')
sys.path.append(os.path.abspath('%s/../src/' % os.path.abspath(os.path.dirname(__file__))))

from stratuslab.Runner import Runner
from stratuslab.Runnable import Runnable
from stratuslab.Util import parseConfig

class MainProgram(Runnable):
    '''A command-line program to run a virtual machine.'''

    def parse(self):
        super(MainProgram, self).parse()
        options = Runner.defaultRunOptions()
        
        self.parser.add_option('-n', '--number', dest='instanceNumber',
                help='number of machine to start', metavar='INT',
                default=options['instanceNumber'], type='int')

        self.parser.add_option('--save', dest='saveDisk', action='store_true',
                help='save image after shutting down the VM',
                default=False)

    def doWork(self):
        config = parseConfig(self.options.configFile)
        runner = Runner(self.image, self.options.__dict__, config)
        runner.runInstance()

if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
