#!/usr/bin/env python

import os
import sys
from optparse import OptionParser

sys.path.append('/usr/lib/stratuslab')
sys.path.append(os.path.abspath('%s/../src/' % os.path.abspath(os.path.dirname(__file__))))

from stratuslab.Util import modulePath
from stratuslab.CommandBase import CommandBase
from stratuslab.InstallatorFactory import InstallatorFactory
from stratuslab.Util import parseConfig

class MainProgram(CommandBase):
    '''A command-line program to install StratusLab.'''

    def __init__(self):
        super(MainProgram, self).__init__()

    def parse(self):
        usage = 'usage: %prog [options]'

        parser = OptionParser(usage=usage)
        parser.add_option('-c', '--config', dest='configFile', 
                          help='configuration file', metavar='FILE',
                          default='%s/conf/stratuslab.cfg' % modulePath)
        
        parser.add_option('-r', '--remove', dest='deRegister', 
                          help='de-register node', action='store_true',
                          default=False)

        # ONE specific parameters
        parser.add_option('-t', '--template', dest='onedTpl', 
                          help='ONe daemon template', metavar='TEMPLATE',
                          default='%s/share/template/oned.conf.tpl' % modulePath)
        parser.add_option('--im', dest='infoDriver', 
                          help='information driver', metavar='IM_NAME', default=None)
        parser.add_option('--vmm', dest='virtDriver',
                          help='virtualization driver', metavar='VM_NAME', default=None)
        parser.add_option('--tm', dest='transfertDriver', 
                          help='transfert driver', metavar='VM_NAME', default=None)
        
        self.options, _ = parser.parse_args()        

    def doWork(self):
        self.checkOptions()
        config = parseConfig(self.options.configFile)
        registrar = Registrar(self.options.__dict__, config)
        registrar.register(self.hostname)
        
