#!/usr/bin/env python
#
# Created as part of the StratusLab project (http://stratuslab.eu),
# co-funded by the European Commission under the Grant Agreement
# INFSO-RI-261552."
#
# Copyright (c) 2010, SixSq Sarl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys

sys.path.append('/var/lib/stratuslab/python')

from stratuslab.ConfigHolder import ConfigHolder
from stratuslab.CommandBase import CommandBaseUser
from stratuslab.marketplace.Deprecator import Deprecator
from stratuslab.Exceptions import InputException
from stratuslab.AuthnCommand import AuthnCommand

# initialize console logging
import stratuslab.api.LogUtil as LogUtil

LogUtil.get_console_logger()


class MainProgram(AuthnCommand):
    """A command-line program to deprecate a StratusLab metadata entry."""

    def __init__(self):
        self.imageid = None
        super(MainProgram, self).__init__()

    def parse(self):
        Deprecator.buildDeprecatorParser(self.parser)

        self.options, self.args = self.parser.parse_args()

    def checkOptions(self):
        if len(self.args) != 1:
            self.parser.error('Please specify an image ID')
        self.imageid = self.args[0]

        Deprecator.checkDeprecatorOptions(self.options, self.parser)

    def doWork(self):
        configHolder = ConfigHolder(self.options.__dict__)
        deprecator = Deprecator(configHolder)

        try:
            deprecatedUrl = deprecator.deprecate(self.imageid)
            print deprecatedUrl
        except InputException, e:
            print e
            sys.exit(1)


if __name__ == '__main__':
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
